### ISSUE TITLE
Make treemacs-rightclick-menu not work.

### ISSUE THREAD

**Issue by zw963** [mrkkrp/ace-popup-menu#9]
If not use this package, treemacs rightclick menu works like this:

![image](https://user-images.githubusercontent.com/549126/129063745-28a85a50-8be3-403a-bf57-28f0b85f6f18.png)

But, if use this pakage, will cause treemacs rightclick menu failed.

**Comment by mrkkrp** [comment]
How did you install `ace-popup-menu`? I cannot reproduce the problem with the current version of the package. I suspect that this got fixed in 594a305704be8ca0ef79a12b787bdb59bc6077c0.

**Comment by zw963** [comment]
Yes, it was fixed now, thank you.
